name: Application CI
on: [push, pull_request]

jobs:
  pipeline:
    name: shopper pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      NODE_VERSION: 18.16.1
      SPRING_JPA_SHOW_SQL: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17.x'
      - name: Install node.js packages
        run: npm install
      - name: Package application
        run: npm run build
      - name: Run backend test
        run: |
            chmod +x mvnw
            npm run ci:backend:test
      - name: Run frontend test
        run: npm run ci:frontend:test
